apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: release-i-03b65-aa583ea
  namespace: default
spec:
  bundlesRef:
    apiVersion: anywhere.eks.amazonaws.com/v1alpha1
    name: bundles-1
    namespace: eksa-system
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
  datacenterRef:
    kind: DockerDatacenterConfig
    name: release-i-03b65-aa583ea
  externalEtcdConfiguration:
    count: 1
  gitOpsRef:
    kind: FluxConfig
    name: eksa-test-20dz2
  kubernetesVersion: "1.23"
  managementCluster:
    name: release-i-03b65-aa583ea
  workerNodeGroupConfigurations:
  - count: 1
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: DockerDatacenterConfig
metadata:
  name: release-i-03b65-aa583ea
  namespace: default
spec: {}

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: eksa-test-20dz2
  namespace: default
spec:
  branch: aws-eks-anywhere-test-release-0-10-3f562c49-398f-464e-8d59-034946877571-18
  clusterConfigPath: aws-eks-anywhere-test-release-0-10-3f562c49-398f-464e-8d59-034946877571-18
  git:
    repositoryUrl: ssh://git@github.com/that-jetpack-guy/aws-eks-anywhere-test-release-0-10-3f562c49-398f-464e-8d59-034946877571-18.git
  systemNamespace: default

---
